[graph_params]  # Parameters for graph representation

voronoi_tol = 0.6
scaling_factor = 1.2
second_order_nn = false

[data]  # Path to folder "Data" containing DFT raw data

root = "/home/santiago/Desktop/GNN/Data"