title = "GNN config file"
author = "Santiago Morandi"

[Graph_params]

# Parameters for converting the DFT raw data to the respective graph representations

voronoi_tol = 0.25
scaling_factorI = 1.5
scaling_factorII = 1.2
second_order_nn = true

[Data]

# Path where data are present

root = "/home/santiago/Desktop/GNN/Data"