[graph_params]  # Parameters for graph representation

voronoi_tol = 0.5
scaling_factor = 1.5
second_order_nn = true

[data]  # Path to folder "Data" containing DFT raw data

root = "/home/santiago/Desktop/GNN/Data"