""" Paths to the folders containing the datasets.
NB: datasets with initial capital letter have different structures than the others."""

from pathlib import Path
from constants import ROOT

paths = {'Intermediates': {'root': ROOT / Path('Intermediates'),
                           'geom': ROOT / Path('Intermediates/structures'),
                           'ener': ROOT / Path('Intermediates/energies.dat'),
                           'dataset': ROOT / Path('Intermediates/Dataset.dat'),
                           'dataset_p': ROOT / Path('Intermediates/Dataset_p.dat')},
         'Benson': {'root': ROOT / Path('Benson'),
                    'geom': ROOT / Path('Benson/structures'),
                    'ener': ROOT / Path('Benson/energies.dat'),
                    'dataset': ROOT / Path('Benson/Dataset.dat'),
                    'dataset_p': ROOT / Path('Benson/Dataset_p.dat')},
         'RPCA': {'root': ROOT / Path('RPCA'),
                  'geom': ROOT / Path('RPCA/structures'),
                  'ener': ROOT / Path('RPCA/energies.dat'),
                  'dataset': ROOT / Path('RPCA/Dataset.dat'),
                  'dataset_p': ROOT / Path('RPCA/Dataset_p.dat')},
         'Alloys': {'root': ROOT / Path('Alloys'),
                    'geom': ROOT / Path('Alloys/structures'),
                    'ener': ROOT / Path('Alloys/energies.dat'),
                    'dataset': ROOT / Path('Alloys/Dataset.dat'),
                    'dataset_p': ROOT / Path('Alloys/Dataset_p.dat')},
         'group2': {'root': ROOT / Path('group2'),
                    'geom': ROOT / Path('group2/structures'),
                    'ener': ROOT / Path('group2/energies.dat'),
                    'dataset': ROOT / Path('group2/Dataset.dat'),
                    'dataset_p': ROOT / Path('group2/Dataset_p.dat')},
         'gas_group2': {'root': ROOT / Path('gas_group2'),
                        'geom': ROOT / Path('gas_group2/structures'),
                        'ener': ROOT / Path('gas_group2/energies.dat'),
                        'dataset': ROOT / Path('gas_group2/Dataset.dat'),
                        'dataset_p': ROOT / Path('gas_group2/Dataset_p.dat')},
         'aromatics': {'root': ROOT / Path('aromatics'),
                    'geom': ROOT / Path('aromatics/structures'),
                    'ener': ROOT / Path('aromatics/energies.dat'),
                    'dataset': ROOT / Path('aromatics/Dataset.dat'),
                    'dataset_p': ROOT / Path('aromatics/Dataset_p.dat')},
         'gas_aromatics': {'root': ROOT / Path('gas_aromatics'),
                    'geom': ROOT / Path('gas_aromatics/structures'),
                    'ener': ROOT / Path('gas_aromatics/energies.dat'),
                    'dataset': ROOT / Path('gas_aromatics/Dataset.dat'),
                    'dataset_p': ROOT / Path('gas_aromatics/Dataset_p.dat')},
         'aromatics2': {'root':  ROOT / Path('aromatics2'), 
                        'geom': ROOT / Path('aromatics2/structures'), 
                        'ener': ROOT / Path('aromatics2/energies.dat'), 
                        'dataset': ROOT / Path('aromatics2/Dataset.dat'),
                        'dataset_p': ROOT / Path('aromatics2/Dataset_p.dat')},
         'gas_aromatics2': {'root':  ROOT / Path('gas_aromatics2'), 
                        'geom': ROOT / Path('gas_aromatics2/structures'), 
                        'ener': ROOT / Path('gas_aromatics2/energies.dat'), 
                        'dataset': ROOT / Path('gas_aromatics2/Dataset.dat'),
                        'dataset_p': ROOT / Path('gas_aromatics2/Dataset_p.dat')},
         'amides': {'root':  ROOT / Path('amides'), 
                        'geom': ROOT / Path('amides/structures'), 
                        'ener': ROOT / Path('amides/energies.dat'), 
                        'dataset': ROOT / Path('amides/Dataset.dat'),
                        'dataset_p': ROOT / Path('amides/Dataset_p.dat')},
         'gas_amides': {'root':  ROOT / Path('gas_amides'), 
                        'geom': ROOT / Path('gas_amides/structures'), 
                        'ener': ROOT / Path('gas_amides/energies.dat'), 
                        'dataset': ROOT / Path('gas_amides/Dataset.dat'),
                        'dataset_p': ROOT / Path('gas_amides/Dataset_p.dat')},
         'carbamate_esters': {'root':  ROOT / Path('carbamate_esters'), 
                        'geom': ROOT / Path('carbamate_esters/structures'), 
                        'ener': ROOT / Path('carbamate_esters/energies.dat'), 
                        'dataset': ROOT / Path('carbamate_esters/Dataset.dat'),
                        'dataset_p': ROOT / Path('carbamate_esters/Dataset_p.dat')},
         'gas_carbamate_esters': {'root':  ROOT / Path('gas_carbamate_esters'), 
                        'geom': ROOT / Path('gas_carbamate_esters/structures'), 
                        'ener': ROOT / Path('gas_carbamate_esters/energies.dat'), 
                        'dataset': ROOT / Path('gas_carbamate_esters/Dataset.dat'),
                        'dataset_p': ROOT / Path('gas_carbamate_esters/Dataset_p.dat')},
         'group2b': {'root':  ROOT / Path('group2b'), 
                        'geom': ROOT / Path('group2b/structures'), 
                        'ener': ROOT / Path('group2b/energies.dat'), 
                        'dataset': ROOT / Path('group2b/Dataset.dat'),
                        'dataset_p': ROOT / Path('group2b/Dataset_p.dat')},
         'gas_group2b': {'root':  ROOT / Path('gas_group2b'), 
                        'geom': ROOT / Path('gas_group2b/structures'), 
                        'ener': ROOT / Path('gas_group2b/energies.dat'), 
                        'dataset': ROOT / Path('gas_group2b/Dataset.dat'),
                        'dataset_p': ROOT / Path('gas_group2b/Dataset_p.dat')},
         'group3S': {'root':  ROOT / Path('group3S'), 
                     'geom': ROOT / Path('group3S/structures'), 
                     'ener': ROOT / Path('group3S/energies.dat'), 
                     'dataset': ROOT / Path('group3S/Dataset.dat'),
                     'dataset_p': ROOT / Path('group3S/Dataset_p.dat')},
         'gas_group3S': {'root':  ROOT / Path('gas_group3S'), 
                         'geom': ROOT / Path('gas_group3S/structures'), 
                         'ener': ROOT / Path('gas_group3S/energies.dat'), 
                         'dataset': ROOT / Path('gas_group3S/Dataset.dat'),
                         'dataset_p': ROOT / Path('gas_group3S/Dataset_p.dat')},
         'group3N': {'root':  ROOT / Path('group3N'), 
                     'geom': ROOT / Path('group3N/structures'), 
                     'ener': ROOT / Path('group3N/energies.dat'), 
                     'dataset': ROOT / Path('group3N/Dataset.dat'),
                     'dataset_p': ROOT / Path('group3N/Dataset_p.dat')},
         'gas_group3N': {'root':  ROOT / Path('gas_group3N'), 
                         'geom': ROOT / Path('gas_group3N/structures'), 
                         'ener': ROOT / Path('gas_group3N/energies.dat'), 
                         'dataset': ROOT / Path('gas_group3N/Dataset.dat'),
                         'dataset_p': ROOT / Path('gas_group3N/Dataset_p.dat')},
         'group4': {'root':  ROOT / Path('group4'), 
                    'geom': ROOT / Path('group4/structures'), 
                    'ener': ROOT / Path('group4/energies.dat'), 
                    'dataset': ROOT / Path('group4/Dataset.dat'),
                    'dataset_p': ROOT / Path('group4/Dataset_p.dat')},
         'gas_group4': {'root':  ROOT / Path('gas_group4'), 
                        'geom': ROOT / Path('gas_group4/structures'), 
                        'ener': ROOT / Path('gas_group4/energies.dat'), 
                        'dataset': ROOT / Path('gas_group4/Dataset.dat'),
                        'dataset_p': ROOT / Path('gas_group4/Dataset_p.dat')},
         'oximes': {'root':  ROOT / Path('oximes'), 
                    'geom': ROOT / Path('oximes/structures'), 
                    'ener': ROOT / Path('oximes/energies.dat'), 
                    'dataset': ROOT / Path('oximes/Dataset.dat'),
                    'dataset_p': ROOT / Path('oximes/Dataset_p.dat')},
         'gas_oximes': {'root':  ROOT / Path('gas_oximes'), 
                        'geom': ROOT / Path('gas_oximes/structures'), 
                        'ener': ROOT / Path('gas_oximes/energies.dat'), 
                        'dataset': ROOT / Path('gas_oximes/Dataset.dat'),
                        'dataset_p': ROOT / Path('gas_oximes/Dataset_p.dat')},
         'amidines': {'root':  ROOT / Path('amidines'), 
                      'geom': ROOT / Path('amidines/structures'), 
                      'ener': ROOT / Path('amidines/energies.dat'), 
                      'dataset': ROOT / Path('amidines/Dataset.dat'),
                      'dataset_p': ROOT / Path('amidines/Dataset_p.dat')},
         'gas_amidines': {'root':  ROOT / Path('gas_amidines'), 
                          'geom': ROOT / Path('gas_amidines/structures'), 
                          'ener': ROOT / Path('gas_amidines/energies.dat'), 
                          'dataset': ROOT / Path('gas_amidines/Dataset.dat'),
                          'dataset_p': ROOT / Path('gas_amidines/Dataset_p.dat')},
         'metal_surfaces': {'root':  ROOT / Path('metal_surfaces'), 
                            'geom': ROOT / Path('metal_surfaces/structures'), 
                            'ener': ROOT / Path('metal_surfaces/energies.dat')}}